name: Build and Conditional Release JovinGit

on:
  push:
    branches: [main]
    tags:
      - 'v*'  # Executa o release apenas para tags
  pull_request:

jobs:
  build:
    name: Build JovinGit
    runs-on: ubuntu-latest

    outputs:
      binary_name: ${{ steps.rename.outputs.binary_name }}

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ pkg-config libgtkmm-3.0-dev

      - name: Build Linux
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Rename if release
        id: rename
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            mv build/JovinGit build/JovinGit-${VERSION}
            echo "binary_name=build/JovinGit-${VERSION}" >> $GITHUB_OUTPUT
          else
            echo "binary_name=build/JovinGit" >> $GITHUB_OUTPUT
          fi

  release:
    name: Create release only tags
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ pkg-config libgtkmm-3.0-dev

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
          VERSION=${GITHUB_REF#refs/tags/}
          mv build/JovinGit build/JovinGit-${VERSION}
      
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-and-release-windows:
    runs-on: ubuntu-latest
    needs: release
    if: github.ref_type == 'tag'

    steps:
      - uses: actions/checkout@v3

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-gtkmm3
          msystem: MINGW64

      - name: Build with MSYS2
        shell: msys2 {0}
        run: |
          cmake -B build-win -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build build-win --config Release

      - name: Upload execut치vel Windows no release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build-win/JovinGit-${{ github.ref_name }}.exe
          asset_name: JovinGit-${{ github.ref_name }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable

      - name: Subir execut치vel para o release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/JovinGit-${{ github.ref_name }}
          asset_name: JovinGit-${{ github.ref_name }}
          asset_content_type: application/octet-stream
