name: Build and Release JovinGit

on:
  push:
    branches: [main]
    tags: ['v*']  # Tags devem começar com 'v'
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake g++ pkg-config libgtkmm-3.0-dev
          
      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          
      - name: Rename Artifact
        id: rename_linux
        run: |
          if [[ "$GITHUB_REF" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            mv build/JovinGit build/JovinGit-$VERSION
            echo "artifact_name=JovinGit-$VERSION" >> $GITHUB_OUTPUT
          else
            echo "artifact_name=JovinGit" >> $GITHUB_OUTPUT
          fi
          
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-bin
          path: build/${{ steps.rename_linux.outputs.artifact_name }}

  build-windows:
    runs-on: windows-latest
    needs: build-linux
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: |
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gtkmm3
          
      - name: Build with MSYS2
        shell: msys2 {0}
        run: |
          mkdir build-win
          cd build-win
          cmake .. -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          
      - name: Rename Windows Artifact
        id: rename_win
        run: |
          $version = $env:GITHUB_REF -replace 'refs/tags/'
          if ($env:GITHUB_REF -like 'refs/tags/*') {
            Rename-Item build-win/JovinGit.exe "JovinGit-$version.exe"
            echo "artifact_name=JovinGit-$version.exe" >> $env:GITHUB_OUTPUT
          } else {
            echo "artifact_name=JovinGit.exe" >> $env:GITHUB_OUTPUT
          }
        shell: pwsh
          
      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-bin
          path: build-win/${{ steps.rename_win.outputs.artifact_name }}

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-bin
          path: release-assets
          
      - name: Download Windows Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-bin
          path: release-assets
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: "Build para Linux e Windows"
          draft: false
          prerelease: false
          files: |
            release-assets/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
